<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 5.0.1 (Python 3.10.5 on win32)" generated="20220711 12:06:52.232" rpa="false" schemaversion="3">
<suite id="s1" name="TestesUsuarios PUT" source="C:\Users\Usuario\Robotron_Beatriz_Jardim_Projeto_Final\usuarios\TestesUsuarios_PUT.robot">
<test id="s1-t1" name="Cenário: PUT Mudar Email de um Usuário para um Existente 400" line="28">
<kw name="Criar Sessao">
<kw name="Create Session" library="RequestsLibrary">
<arg>serverest</arg>
<arg>http://localhost:3000</arg>
<doc>Create Session: create a HTTP session to a server</doc>
<msg timestamp="20220711 12:06:52.365" level="INFO">Creating Session using : alias=serverest, url=http://localhost:3000, headers={},                     cookies={}, auth=None, timeout=None, proxies=None, verify=False,                     debug=0 </msg>
<status status="PASS" starttime="20220711 12:06:52.364" endtime="20220711 12:06:52.365"/>
</kw>
<status status="PASS" starttime="20220711 12:06:52.364" endtime="20220711 12:06:52.365"/>
</kw>
<kw name="PUT Editar id &quot;0uxuPY0cbmQhpEz1&quot; com Email Existente" sourcename="PUT Editar id &quot;${id}&quot; com Email Existente">
<kw name="Create Dictionary" library="BuiltIn">
<var>&amp;{payload}</var>
<arg>nome=Frank Ocean</arg>
<arg>email=badlands@gmail.com</arg>
<arg>password=ivy</arg>
<arg>administrador=true</arg>
<doc>Creates and returns a dictionary based on the given ``items``.</doc>
<msg timestamp="20220711 12:06:52.366" level="INFO">&amp;{payload} = { nome=Frank Ocean | email=badlands@gmail.com | password=ivy | administrador=true }</msg>
<status status="PASS" starttime="20220711 12:06:52.366" endtime="20220711 12:06:52.366"/>
</kw>
<kw name="PUT On Session" library="RequestsLibrary">
<var>${response}</var>
<arg>serverest</arg>
<arg>/usuarios/${id}</arg>
<arg>data=&amp;{payload}</arg>
<arg>json=None</arg>
<arg>expected_status=anything</arg>
<doc>Sends a PUT request on a previously created HTTP Session.</doc>
<msg timestamp="20220711 12:06:56.482" level="WARN">Retrying (RetryAdapter(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001F638E344F0&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /usuarios/0uxuPY0cbmQhpEz1</msg>
<msg timestamp="20220711 12:07:00.784" level="WARN">Retrying (RetryAdapter(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001F638E34760&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /usuarios/0uxuPY0cbmQhpEz1</msg>
<msg timestamp="20220711 12:07:05.268" level="WARN">Retrying (RetryAdapter(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001F638E348E0&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /usuarios/0uxuPY0cbmQhpEz1</msg>
<msg timestamp="20220711 12:07:09.373" level="FAIL">ConnectionError: HTTPConnectionPool(host='localhost', port=3000): Max retries exceeded with url: /usuarios/0uxuPY0cbmQhpEz1 (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001F638E34AF0&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))</msg>
<status status="FAIL" starttime="20220711 12:06:52.366" endtime="20220711 12:07:09.404"/>
</kw>
<kw name="Log To Console" library="BuiltIn">
<arg>${response.content}</arg>
<doc>Logs the given message to the console.</doc>
<status status="NOT RUN" starttime="20220711 12:07:09.405" endtime="20220711 12:07:09.406"/>
</kw>
<kw name="Set Global Variable" library="BuiltIn">
<arg>${response}</arg>
<doc>Makes a variable available globally in all tests and suites.</doc>
<status status="NOT RUN" starttime="20220711 12:07:09.406" endtime="20220711 12:07:09.406"/>
</kw>
<status status="FAIL" starttime="20220711 12:06:52.366" endtime="20220711 12:07:09.407"/>
</kw>
<kw name="Validar Status Code &quot;400&quot;" sourcename="Validar Status Code &quot;${statuscode}&quot;">
<status status="NOT RUN" starttime="20220711 12:07:09.409" endtime="20220711 12:07:09.409"/>
</kw>
<kw name="Validar Mensagem: &quot;Este email já está sendo usado&quot;" sourcename="Validar Mensagem: &quot;${mensagem}&quot;">
<status status="NOT RUN" starttime="20220711 12:07:09.409" endtime="20220711 12:07:09.410"/>
</kw>
<tag>PUT400</tag>
<status status="FAIL" starttime="20220711 12:06:52.363" endtime="20220711 12:07:09.411">ConnectionError: HTTPConnectionPool(host='localhost', port=3000): Max retries exceeded with url: /usuarios/0uxuPY0cbmQhpEz1 (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001F638E34AF0&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))</status>
</test>
<doc>Arquivo simples para requisições HTTP em APIs</doc>
<status status="FAIL" starttime="20220711 12:06:52.235" endtime="20220711 12:07:09.414"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
<stat pass="0" fail="1" skip="0">PUT400</stat>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="TestesUsuarios PUT">TestesUsuarios PUT</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20220711 12:06:56.482" level="WARN">Retrying (RetryAdapter(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001F638E344F0&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /usuarios/0uxuPY0cbmQhpEz1</msg>
<msg timestamp="20220711 12:07:00.784" level="WARN">Retrying (RetryAdapter(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001F638E34760&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /usuarios/0uxuPY0cbmQhpEz1</msg>
<msg timestamp="20220711 12:07:05.268" level="WARN">Retrying (RetryAdapter(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001F638E348E0&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /usuarios/0uxuPY0cbmQhpEz1</msg>
</errors>
</robot>
